### ISSUE TITLE
Add an option to automatically download the CLI

### ISSUE THREAD

**Issue by stefanprodan** [istio/get-istioctl#2]
It would be great to have an option for the action to download istioctl and place it on the GH runner path, something like:

```
      - name: Install istioctl
        id: get-istioctl
        uses: istio/get-istioctl@main
        with:
          version: "1.*"
          install: true
```
